name: CI/CD

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        node: [16.x, 18.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Node 🧰
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Install 📦
      run: npm ci

    - name: Lint 🔎
      run: |
        npm run ts:check
        npm run lint

    - name: Test 🐛 + Coverage 🌈
      run: npm run coverage


  deploy:
    needs: [test]
    runs-on: macos-latest

    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Cache 💾 # https://nextjs.org/docs/messages/no-cache#github-actions
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Node 🧰
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install 📦
      run: npm ci

    - name: Build 🔧
      run: |
        npm run build
        npm run export
      env:
        NEXT_PUBLIC_CL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CL_CLIENT_ID }}
        NEXT_PUBLIC_CL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CL_ENDPOINT }}

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: out
        single-commit: false
