name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.17.0, 18.x, 20.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Node 🧰
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Install 📦
      run: npm ci

    - name: Lint 🔎
      run: |
        npm run ts:check
        npm run lint

    - name: Test 🐛 + Coverage 🌈
      run: npm run coverage
